#!/bin/bash

# Define the DOTFILES directory
DOTFILES="$HOME/dotfiles"

# Navigate to the dotfiles directory
pushd "$DOTFILES" || exit

# Stow all relevant configurations
stow -t ~/.config nvim  # LazyVim configuration
stow tmux               # Tmux configuration
stow zsh                # Zsh configuration
stow -t ~/.config ghostty  # Ghostty configuration

# Return to the previous directory
popd || exit

